### ISSUE TITLE
New release for hanami version 1.0

### ISSUE THREAD

**Issue by freework-tech** [artemeff/newrelic-hanami#6]
First of all thanks for creating such a nice gem
Could you create a new release on rubygems which works for hanami version 1.0?

**Comment by davydovanton** [comment]
@freework-tech hey, newrelic-hanami works with hanami <2 versions. Why do we need to update gem version in rubygems? :)

**Comment by benbachhuber** [comment]
@davydovanton If I put gem 'newrelic-hanami' without specifying the github repository as source it gets the old version of newrelic-hanami(without the 1.0 hanami support) from rubygems

**Comment by nessur** [comment]
fix the published rubygems version, please :)

**Comment by nessur** [comment]
https://rubygems.org/gems/newrelic-hanami/versions/0.4.3
says "hanami-controller < 1.0.0, > 0.4.0"
even though this project's .gemspec says " < 2" for the constraint

**Comment by guilherme** [comment]
could you please fix the published version?

**Comment by zafarabbas** [comment]
Please publish a new version which supports "hanami-controller" > 1.0

@artemeff @davydovanton ^

**Comment by artemeff** [comment]
released 0.4.4, sorry for delay
